### PR TITLE
Add support for Experiment model

### LINKED ISSUE #20: Introduce an experiment entity into DAP data hierarchy
It should store experiment start date and a wave shape (the wave shape will come from the modelling team as discussed in the meeting).

### PR DESCRIPTION
**Pull request by nowakowski**
Fixes #20

### CODE REVIEW

**Comment by nowakowski** [comment]
@dharezlak @mkasztelnik Deployed on dap-dev. Please report any issues in this PR.

**Comment by dharezlak** [comment]
@nowakowski: can you store a few sample experiments just to have something to play with?

**Comment by nowakowski** [comment]
@dharezlak Created two dummy experiments on dap-dev (2 timelines each).

**Comment by mkasztelnik** [comment]
@nowakowski `Experiment` `start_date` and `end_date` should be mandatory.

**Comment by mkasztelnik** [comment]
@nowakowski How I can fetch timelines assigned to the experiment? Currently following response is returned:

```
{"experiments":[{"id":1,"name":"Eksperyment 1","description":"Przykładowy eksperyment do testowania UI","start_date":"2015-09-22T07:03:01.782Z","end_date":"2015-10-06T07:03:01.782Z","levee_id":1},{"id":2,"name":"Eksperyment 2","description":"Przykładowy eksperyment do testowania UI","start_date":"2015-09-27T07:03:55.235Z","end_date":"2015-10-04T07:03:55.235Z","levee_id":1}]}
```

no information about timelines attached to each `Experiment`

**Comment by nowakowski** [comment]
Date validations added. Timeline/Experiment assignment can be fetched via `GET /timelines?experiment_id=xxx`.

**Comment by nowakowski** [comment]
@mkasztelnik Added rake task which creates sample experiments. Usage: run `bundle exec rake experiment:create_sample RAILS_ENV=production` in DAP directory. Deployed on dap-dev.

**Comment by mkasztelnik** [comment]
:+1: IMHO it can be merged into master

**Pull request merged**
