### PR TITLE
Update to active model serializers 0.10.0.rc3

### PR DESCRIPTION
**Pull request by mkasztelnik**
It will allow use to add cache to every object serialized into JSON. See https://github.com/rails-api/active_model_serializers#caching for details.

### CODE REVIEW

**Comment by mkasztelnik** [comment]
@nowakowski. @bwilk can you take a look at this PR?

**Comment by nowakowski** [comment]
@mkasztelnik I'm having doubts. I see you have removed `embed ids` in all serializers; however IIRC some of those are actually required (or at least expected) by the UI. I have deployed your branch to dap-dev and now I see that the UI (at ui-dev) returns no readings for any of the sensors displayed on the overhead map. Could I ask @mkasztelnik @dharezlak to verify that the UI is still compatible with the proposed branch?

**Comment by mkasztelnik** [comment]
@nowakowski please read AMS documentation for 0.10.0 version - they changed the way how serialization works. To summarize: serialization is moved into adapter. `json` adapter (configured [here](https://github.com/ismop/dap/blob/ams_0.10.0.rc3/config/initializers/active_model_serializers.rb#L1)) does what we need, it converts relations into `ids`.

**Comment by mkasztelnik** [comment]
According to no data shown on overhead map: there is simply no new data in DAP-DEV. Following request is send (you can trace it using e.g. chrome development tools):

```
http://DAP-DEV/api/v1/measurements?timeline_id=552&time_from=2015-10-06T10%3A31%3A08.264%2B02%3A00&time_to=2015-10-09T10%3A31%3A08.264%2B02%3A00&quantity=1000
```

@nowakowski, @bwilk please check if flum sink is working correctly on both environment (prod and dev).

To conclude this situation is not caused by the change introduced in this PR.

**Comment by nowakowski** [comment]
OK; that's because flume sinks aren't currently configured to push data into dap-dev. I'm going to merge this PR.

**Pull request merged**
