### PR TITLE
Update scenario model

### LINKED ISSUE #55: Add name and description into Scenario
These fields will be used on UI

### PR DESCRIPTION
**Pull request by nowakowski**
Fixes #55

### CODE REVIEW

**Comment by nowakowski** [comment]
@mkasztelnik @bwilk Note: I had to temporarily remove `result.threat_level` - this will be replaced by the structure proposed by @tbartynski in a separate PR.

**Comment by nowakowski** [comment]
@mkasztelnik I know you're not nominally my PR reviewer but could you take a brief look at this and tell me whether it's consistent with your expectations? I need this merged to continue work on @tbartynski's `ThreatAssessment` update.

**Comment by mkasztelnik** [comment]
Model looks ok, but controller for fetching scenarios for a given experiment is missing.

**Comment by nowakowski** [comment]
@mkasztelnik Updated.

**Comment by mkasztelnik** [comment]
Can you also add possibility to find all `Scenarios` for a given list of `Timelines` (sorry I forgot about it before...)?

**Comment by nowakowski** [comment]
@mkasztelnik Done as requested. Do you think we could merge it now?

**Comment by mkasztelnik** [comment]
Ok. Please deploy it into dap-dev

**Comment by nowakowski** [comment]
That's what we like to hear. :) On it.

**Comment by nowakowski** [comment]
@mkasztelnik It's on dap-dev now. Good luck!

**Pull request merged**
