### PR TITLE
Extend Scenario model with threat_level field

### LINKED ISSUE #130: Implement changes in Scenario model
- Add a field named `threat_level` (int)
- Add `scenarios.name`, `scenarios.description` and `scenarios.threat_level` to `ThreatLevelController` output
- Remove TB's obsolete calculator service
- Fix specs etc.

### PR DESCRIPTION
**Pull request by nowakowski**
Fixes #130

### CODE REVIEW

**Comment by nowakowski** [comment]
@mkasztelnik @mpawlik There are 98 existing Scenarios in the production DB. The default value of the new `threat_level` field is 0 but perhaps I need to compute proper values for each existing Scenario? If so, what algorithm should I apply?

**Comment by mkasztelnik** [comment]
Random :dancer: 

But to be serious these scenarios were used to show "Analyse" features during "demo day". Most probably all existing scenarios can be removed - @mpawlik do you have anything against it? Are you using them in "portostawiaczka"?

**Comment by nowakowski** [comment]
You mean "porównywaczka"? ;)

**Comment by mkasztelnik** [comment]
Sure :smile_cat:

**Comment by mpawlik** [comment]
@mkasztelnik some (if not all) of old scenarios are required for 'porownywaczka' to work (be able to store results), so until we obtain a new set it would be best to keep the old scenarios.

@nowakowski I'm OK with 0 threat level for all available scenarios. We'll update the value by hand later on, so it looks nice in UI:).

**Comment by mpawlik** [comment]
@nowakowski I've just added 25 new scenarios, please include them when doing the threat level update.

**Comment by mkasztelnik** [comment]
If these timelines are needed than please assign them into scenarios to make `threat_levels` REST API work.

**Comment by mpawlik** [comment]
Did you mean assign scenarios to experiments? If so I just did it (old scenarios are assigned to czerwiec's experiment), and threat_levels service still returns 500.

**Comment by mkasztelnik** [comment]
Yeach because there are timelines assigned to experiment which are not assigned to any scenario.

**Comment by mpawlik** [comment]
The only two timelines (I could find) with this association are 'wysokosc fali' so I'm not sure what to do about it. Assign them to a fake scenario?

As a side note - we could drop the timeline->experiment association altogether if it's used only for fala's wysokosc.

**Comment by mkasztelnik** [comment]
No "wysokosc fali" is ok. As a conclusion my previous comment can be not correct, it should be investigated why 500 is still returned.

**Comment by nowakowski** [comment]
@mkasztelnik I think you're confusing relationships a bit. ;) The error has nothing to do with timelines. `GET threat_levels` throws 500 because there are 94 `Result` objects in the DB not assigned to any `Scenario` and the controller assumes that a result will always have a linked scenario (which is quite reasonable). @mpawlik Take a look at #129 and tell me what to do about the existing `Result` objects.

**Comment by nowakowski** [comment]
Since nobody commented, I simply assigned all existing `Result` objects to a random scenario.

**Pull request merged**
