### PR TITLE
Update august experiment interval and water wave

### PR DESCRIPTION
**Pull request by mkasztelnik**
Previous experiment was skipped due to technical levee problems. Current changes are connected with new experiment concept which already took place.

Experiment changes are already applied into prod and dev dap.

### CODE REVIEW

**Comment by nowakowski** [comment]
@mkasztelnik I tend to follow a general rule that all custom rake tasks should be idempotent. This is to avoid trashing the production DB in case of multiple invocations (which happens surprisingly often). Please consider the following:

- Use `find_or_create_by` instead of `create` when spawning data structures
- Before inserting new measurements, purge all existing `measurements` which belong to this experiment's simulated timeline

**Comment by nowakowski** [comment]
@mkasztelnik What's the status of this PR?

**Comment by mkasztelnik** [comment]
According to our f2f conversation you said that you will do polishing and merging. Additionally (in another PR) I propose to create dedicated function allowing to create water wave, eg. something like:

```ruby
create_experiment(name: "Experiment n", from: Time.now, to: Time.now + 70.hours,
                               Function.new(from: 0.0, to: 4.0, interval: 24.hours), # up
                               Function.new(from: 4.0, to: 4.0, interval: 10.hours), # plato
                               Function.new(from: 4.0, to: 0.0, interval: 36.hours)) # down
```

This method can check if experiment with given name already exists. It yes than existing water wave is deleted and new one is generated. I can help in implementing this method next week.

**Comment by nowakowski** [comment]
Right - sorry; I forgot about that convo. :)

**Pull request merged**
