### PR TITLE
Script for creating August experiment

### PR DESCRIPTION
**Pull request by mkasztelnik**
Already done on dev and prod

### CODE REVIEW

**Comment by nowakowski** [comment]
Okay, but why "sierpien" everywhere?

**Comment by mkasztelnik** [comment]
Why not, do you have better proposition?

**Comment by nowakowski** [comment]
sierpień with a "ń". :)

**Comment by mkasztelnik** [comment]
I was not sure if polish letters are supported. I will fix it.

**Comment by mkasztelnik** [comment]
Fixes in script and on dev and prod.

**Pull request merged**
